### PR TITLE
[WIP] Upgrade dependency to AWS v3

### PR DESCRIPTION
**Pull request by bakura10**
Hi,

ping @basz @juriansluiman 

This PR upgrades the module to the new AWS SDK v3, which brings many advantages (more performance, PSR7 support, and above all because all new features in AWS are only supported in the new SDK...).

As a conseuqence this brings dependency to PHP 5.5

I'd like to bump all other SlmQueue module to PHP 5.5 too before merging this PR.

### CODE REVIEW

**Comment by basz** [comment]
no issues with bumping PHP version my side. I'll prepare a PR for the Doctrine module this week.

**Comment by bakura10** [comment]
We should first merge that: https://github.com/juriansluiman/SlmQueue/pull/165 :)

**Comment by iam-merlin** [comment]
@bakura10 I just abort a dumb PR to let you the lead on that. 

From what I've seen and my knowledge of aws-php all your changes seem to be good and travis failed only because your tests are not completely updated.

It's not a big deal, do you plan to update this PR soon? I can PR to aws-v3 with the require change (but I'll be available for work only in septembre) if you want.

**Comment by bakura10** [comment]
Hi,

I wanted to wait on SlmQueue 0.5 to have new features (in addition of raising dependency), but I think I will tag 0.5 sooner so I can update this one too :).

Remind me in one week if I forget.

**Comment by iam-merlin** [comment]
:+1:

**Comment by iam-merlin** [comment]
@bakura10 ping ^^

**Comment by bakura10** [comment]
@iam-merlin , just asked if I can merge SlmQueue 0.5: https://github.com/juriansluiman/SlmQueue/issues/166

Once merge I'll fix that!

**Comment by iam-merlin** [comment]
@basz what do you think for merging?

**Comment by basz** [comment]
I don't lead this project. Also a bit confused about the release plan for v0.5. Ping @bakura10

**Comment by iam-merlin** [comment]
oops, sorry. So the ping is done ^^.

**Comment by bakura10** [comment]
Yeah I agree, the 0.5 release, as of now, is only "bumping dependency and using short array notation", to allow SlmQueueSqs to use the newer SDK. @juriansluiman , do you allow me to tag SlmQueue as 0.5 ? It will likely need you and @basz to release a new version of SlmQueueDoctirne and SlmQueueBeanstalk (the only change will be changing the composer.json dependencies).

**Comment by jackdpeterson** [comment]
Ping for integration / re-tagging.

I'd just prefer to not pin my composer.json to the dev-aws-v3 branch.

**Comment by jackdpeterson** [comment]
It also looks like instantiation of the Sqs service is incompatible with the way that the Aws SDK expects construction.

is:
->create('sqs');

should:
->createSqs();

**Comment by iam-merlin** [comment]
Hi @jackdpeterson, I've forked the project for testing purpose a few month ago with the V3 integration. It's only for testing purpose because we moved to AWS lambda. From my memories, it's functional and it use the v2 ZF2 module with the last version of AWS SDK PHP. You can have a look to our commits to see what we changed.

[The fork here](https://github.com/eoko/SlmQueueSqs)

**Comment by bakura10** [comment]
Unrelated @iam-merlin : did you move all your code to AWS Lambda? :o

**Comment by iam-merlin** [comment]
@bakura10 for a current project only. If it's a success (in production), we will. 

FYI, in our current project, we used Lambda and dynamoDB (Stream) for dispatching events through different channels like emails, sms, notifications... and different group of target. For example, if I have an event that should be sent by email and sms to all members for the organization "x", I just have to persist that event in DynamoDB and Lambda will do the rest.

Today, our results on Lambda are very very promising :). (and develop on NodeJS is refreshing). So, our next step will be to couple Lambda with SQS to create a resilient service.

Hope that is interesting.

**Comment by bakura10** [comment]
Definitely interesting. I wanted to do the same but unforutnately I'm having a hard time architecturing something a bit more complex than a simple demo :);

**Comment by iam-merlin** [comment]
It's about architecturing a ZF3 component or it's unrelated too? :P

**Comment by bakura10** [comment]
It's mostly that I can't use PHP with it :p.

**Comment by iam-merlin** [comment]
lol

**Comment by jackdpeterson** [comment]
Ian, you changes in the fork are right along the lines of what i was about to do myself. I quickly discovered the issue with null values on those queues. Can we just integrate your fork into this upstream and call it  0.5?

**Comment by juriansluiman** [comment]
In collaboration with @bakura10, I would indeed love to incorporate the latest AWS module changes into this library. If there is any good fork, feel free to PR / merge.

**Comment by bakura10** [comment]
Hi, I'm going to do that and tagging SlmQueue 0.5 first.

@jackdpeterson your PR completely replace mine right?

**Comment by bakura10** [comment]
Overseeds by #32

**Comment by jackdpeterson** [comment]
@bakura10 -- the one I opened in #32 for Ian's repo is the correct one to merge in. He was a number of steps ahead of where I was headed.

**Pull request closed without merging**
